version: "3.9"

services:
  backend:
    build: ./be
    container_name: django_backend_jeongneung-survey
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./be/.env
    expose:
      - "8000"
    depends_on:
      - db_user
    networks:
      - kioedu_network

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./fe:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "build"]
    networks:
      - kioedu_network

  nginx:
    image: nginx:stable-alpine
    container_name: jeongneung-survey_nginx
    ports:
      - "8090:80"
      - "9443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fe/build:/usr/share/nginx/html
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend
    networks:
      - kioedu_network

  db_user:
    image: postgres:16
    container_name: survey_db
    restart: always
    environment:
      POSTGRES_DB: kioedu
      POSTGRES_USER: rheavision
      POSTGRES_PASSWORD: 16444907
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - kioedu_network

networks:
  kioedu_network:
    external: true
    name: kioedu_network

volumes:
  static_volume:
  media_volume:
  pgdata_user:
